{{- if .Values.serviceMonitors.kafka.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-kube-prometheus-kafka  # Le nom est correct
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: prometheus-operator  # Match avec le sélecteur
    release: {{ .Release.Name }}
spec:
  groupVersion: {{ .Values.serviceMonitors.kafka.groupVersion }}  # Référence à values.yaml
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
      - kafka-dev
{{- end }}